---
abstract: 'Setup a class with shortcut methods to the sources of a DBIx::Class-based schema'
author:
  - 'Pedro Melo <melo@cpan.org>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBICx-Shortcuts
requires:
  Carp: 0
  DBIx::Class: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0.92
  parent: 0
resources:
  repository: http://github.com/melo/dbicx-shortcuts/
version: 0.006
